# This YAML file contains attacher & csi driver API objects,
# which are necessary to run external csi provisioner for opensds.

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.csipluginProvisioner.name }}
  labels:
    app: {{ template "csipluginProvisioner.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "csipluginProvisioner.fullname" . }}
    release: {{ .Release.Name }}
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ template "csipluginProvisioner.fullname" . }}
  labels:
    app: {{ template "csipluginProvisioner.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ .Values.csipluginProvisioner.name }}
  replicas: {{ .Values.csipluginProvisioner.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "csipluginProvisioner.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "csipluginProvisioner.fullname" . }}
      labels:
        app: {{ template "csipluginProvisioner.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccount: csi-provisioner-file
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.1.0
          args:
            - "--provisioner=csi-opensdsplugin"
            - "--csi-address=$(ADDRESS)"
            - "--connection-timeout=15s"
            - "--feature-gates=Topology=True"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: {{ template "csipluginProvisioner.fullname" . }}
          image: {{ .Values.image }}
          args :
            - "--csiEndpoint=$(CSI_ENDPOINT)"
            - "--opensdsEndpoint=$(OPENSDS_ENDPOINT)"
            - "--opensdsAuthStrategy=$(OPENSDS_AUTH_STRATEGY)"
            - "--v=8"
          env:
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: OPENSDS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: opensdsendpoint
            - name: OPENSDS_AUTH_STRATEGY
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: opensdsauthstrategy
            - name: OS_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: osauthurl
            - name: OS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: osusername
            - name: PASSWORD_ENCRYPTER
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: passwordencrypter
            - name: OS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: ospassword
            - name: PASSWORD_ENCRYPTER
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: passwordencrypter
            - name: ENABLE_ENCRYPTED
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: enableEncrypted
            - name: OS_TENANT_NAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: ostenantname
            - name: OS_PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: osprojectname
            - name: OS_USER_DOMAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-opensdsplugin-file
                  key: osuserdomainid
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: certificate-path
              mountPath: /opt/opensds-security
      volumes:
        - name: socket-dir
          emptyDir:
        - name: certificate-path
          hostPath:
            path: /opt/opensds-security
            type: DirectoryOrCreate
