# Copyright 2018 The soda Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: create sushi work directory if it doesn't exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ sushi_work_dir }}"

- name: include scenarios/repository.yml when installing from repository
  include: scenarios/repository.yml
  when: install_from == "repository"

- name: include scenarios/release.yml when installing from release
  include: scenarios/release.yml
  when: install_from == "release"

- name: include scenarios/flexvolume.yml when sushi plugin type is flexvolume
  include: scenarios/flexvolume.yml
  when: sushi_plugin_type == "flexvolume"

- name: include scenarios/csi.yml when sushi plugin type is csi
  include: scenarios/csi.yml
  when: sushi_plugin_type == "csi"
