# This YAML defines all API objects to create ServiceAccount roles for csi node plugin.
{{- if .Values.serviceAccounts.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-nodeplugin-block
{{- end }}