# This YAML file contains ServiceAccount API objects,
# which are necessary to run external csi provisioner for opensds.
{{- if .Values.serviceAccounts.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-provisioner-block
{{- end }}