# This YAML file contains configmap objects,
# which are necessary to run csi soda plugin.

kind: ConfigMap
apiVersion: v1
metadata:
  name: csi-configmap-sodaplugin-block
data:
  sodaendpoint: {{ .Values.data.sodaEndpoint }}
  sodaauthstrategy: {{ .Values.data.sodaAuthStrategy }}
  osauthurl: {{ .Values.data.osAuthURL }}
  osusername: {{ .Values.data.osUsername }}
  ospassword: {{ .Values.data.osPassword }}
  ostenantname: {{ .Values.data.osTenantName }}
  osprojectname: {{ .Values.data.osProjectName }}
  osuserdomainid: {{ .Values.data.osUserDomainId }}
  passwordencrypter: {{ .Values.data.passwordEncrypter }}
  enableEncrypted: {{ .Values.data.enableEncrypted }}
