{
 "title": "Performance Monitor - Overall",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "filters", "label": "Filters" }
  ]
 },
 "panels": [
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "storage_responseTime", "legendFormat": "Storage ID: {{storage_id}} " }
   ]
  },
  { "title": "Storage Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Storage Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "storage_throughput", "legendFormat": "Storage ID: {{storage_id}}" }
   ]
  },
  {
   "title": "Storage Read Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "storage_readThroughput", "legendFormat": "Storage ID: {{storage_id}}" }
   ]
  },
  {
   "title": "Storage Write Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "storage_writeThroughput  ", "legendFormat": "Storage ID: {{storage_id}}" }
   ]
  },
  { "title": "Storage Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Storage Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    { "expr": "storage_requests", "legendFormat": "Storage ID: {{storage_id}}" }
   ]
  },
  {
   "title": "Storage Read Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    { "expr": "storage_readRequests", "legendFormat": "Storage ID: {{storage_id}}" }
   ]
  },
  {
   "title": "Storage Write Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    { "expr": "storage_writeRequests", "legendFormat": "Storage ID: {{storage_id}}" }
   ]
  }
 ]
}