# Default values for soda csi plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image: sodafoundation/csiplugin-block:v1.4.0
# ImagePullPolicy: valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: IfNotPresent
# ImageRestartPolicy: valid values are "Never", and "Always"
imageRestartPolicy: Never
# Please modify data fields in real environment
data:
  sodaEndpoint: http://127.0.0.1:50040
  sodaAuthStrategy: keystone
  osAuthURL: http://127.0.0.1/identity
  osUsername: admin
  osPassword: soda@123
  osTenantName: admin
  osProjectName: admin
  osUserDomainId: default
  passwordEncrypter: aes
  enableEncrypted: F

# csipluginProvisioner spec
csipluginProvisioner:
  name: csi-provisioner-sodaplugin-block
  replicaCount: 1
# csipluginAttacher spec
csipluginAttacher:
  name: csi-attacher-sodaplugin-block
  replicaCount: 1
# csipluginNodeplugin spec
csipluginNodeplugin:
  name: csi-nodeplugin-sodaplugin-block
  replicaCount: 1
# csipluginSnapshotter spec
csipluginSnapshotter:
  name: csi-snapshotter-sodaplugin-block
  replicaCount: 1
