# Copyright (c) 2019 The OpenSDS Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: uninstall opensds orchestration manager
  shell: "{{ item }}"
  with_items:
    - kill -9 `lsof -i :5000 |  grep 5000 | awk '{print $2}'`
  args:
    chdir: "{{ st2_installer_work_dir }}"
    warn: false
  ignore_errors: yes
  become: yes

- name: bring down stackstorm docker instances
  shell: "{{ item }}"
  with_items:
    - docker-compose down
  args:
    chdir: "{{ st2_installer_work_dir }}"
    warn: false
  ignore_errors: yes
  become: yes
  
