# This is the GitHub Action to run the CI for SODA Installer for all pull requests

name: SODA Installer CI

# Controls when the action will run. 
# Triggers the workflow on push or pull request events but only for the main branch
# Allows you to run this workflow manually from the Actions tab
on: [pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-18.04, ubuntu-20.04]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: ${{ matrix.go-version }}
          # Whether to download only stable versions
          stable: true # optional, default is true
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout the repository
        uses: actions/checkout@v2
      
      - name: List ansible sources in the runtime
        run: |
            echo "Installed Ansible Version in Runtime: "
            ansible --version
        
      #- name: Remove latest ansible on Ubuntu 18.04
      #  run: |
      #      echo "uninstall with pipx"
      #      pipx uninstall ansible-core
      #  if: ${{ matrix.os == 'ubuntu-18.04' }}

      # Change the permissions of the ansible installer
      - name: 'Make ansible installer executable and run install ansible on OS: ${{ matrix.os }}'
        run: |
            sudo chmod +x ./ansible/install_ansible.sh
            ./ansible/install_ansible.sh
        shell: bash
        env:
          CI: true
        if: ${{ always() }}

      - name: 'Make the CI check executable and initiate the testing with SODA Containers'
        run: |
          sudo chmod +x ./ci/ci_check.sh
          ./ci/ci_check.sh container
        shell: bash
        env:
          GOPATH: "/home/runner/work/installer/"
        if: ${{ always() }}

      - name: 'Make the CI check executable and initiate the testing with SODA repository'
        run: |
          sudo chmod +x ./ci/ci_check.sh
          ./ci/ci_check.sh repository
        shell: bash
        env:
          GOPATH: "/home/runner/work/installer/"
        if: ${{ always() }}
      
      - name: 'Make the CI check executable and initiate the testing with SODA release'
        run: |
          sudo chmod +x ./ci/ci_check.sh
          ./ci/ci_check.sh release
        shell: bash
        env:
          GOPATH: "/home/runner/work/installer/"
        if: ${{ always() }}

      - name: 'Uninstall SODA release and clean up'
        run: |
          sudo chmod +x ./ci/ci_check.sh
          ./ci/ci_check.sh uninstall_release
        shell: bash
        env:
          GOPATH: "/home/runner/work/installer/"
        if: ${{ always() }}
